"""Default API registry (same contract as legacy Streamlit app)."""

DEFAULT_API_CONFIGS: list[dict] = [
    {
        "name": "get_org_info",
        "description": "获取企业信息",
        "method": "GET",
        "endpoint": "/org/info",
        "default_params": {},
        "resolvers": {},
        "response_key": "result",
        "pagination": False,
    },
    {
        "name": "query_projects",
        "description": "查询项目列表 (游标分页)",
        "method": "GET",
        "endpoint": "/v3/project/query",
        "default_params": {"pageSize": 50},
        "resolvers": {"pageToken": "from_context"},
        "response_key": "result",
        "pagination": True,
    },
    {
        "name": "search_project_stages",
        "description": "查询项目阶段 (Kanban列)",
        "method": "GET",
        "endpoint": "/v3/project/{projectId}/stage/search",
        "default_params": {"pageSize": 50},
        "resolvers": {"projectId": "from_context"},
        "response_key": "result",
        "pagination": True,
    },
    {
        "name": "query_tasks",
        "description": "查询任务详情 (支持 filter.projectId)",
        "method": "GET",
        "endpoint": "/v3/task/query",
        "default_params": {"pageSize": 50},
        "resolvers": {"filter": "build_task_filter", "pageToken": "from_context"},
        "response_key": "result",
        "pagination": True,
    },
    {
        "name": "get_task_worktime",
        "description": "获取任务工时聚合",
        "method": "GET",
        "endpoint": "/worktime/aggregation/task/{taskId}",
        "default_params": {},
        "resolvers": {"taskId": "from_context"},
        "response_key": "result",
        "pagination": False,
    },
]
